version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    
    docker:
      - image: cimg/python:3.10.2

    working_directory: /app
    
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

      - persist_to_workspace:
          root: /app
          paths:
            - models/

     
workflows:
  test: 
    jobs:
      - build-and-test
